apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  mysql-username: YWRtaW4=
  mysql-password: MjJKdW1wU3RyZWV0IQ==
  mongo-uri: bW9uZ29kYitzcnY6Ly9hZG1pbjoyMkp1bXBTdHJlZXQlMjFAYXRsYXMtY2x1c3Rlci55dWF2YW15Lm1vbmdvZGIubmV0L29yZGVyc2VydmljZWRi
  